### ISSUE TITLE
Export interfaces?

### ISSUE THREAD

**Issue by strogonoff** [paneron/libmmel#2]
It’s very difficult to use libmmel because all types/interfaces are private and cannot be imported.

**Comment by ribose-jeffreylau** [comment]
<del>Which specific interfaces does Paneron need that have to be exported?</del>

UPDATE: Agreed to have all interfaces exposed at the top-level.

**Comment by strogonoff** [comment]
Thank you! Per discussion elsewhere, I am now using deep imports, feel free to close…

**Comment by ribose-jeffreylau** [comment]
Superseded by #3.
